name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:     # manual trigger option

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your fork
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add upstream and fetch
      run: |
        git remote add upstream https://github.com/oraxen/oraxen.git
        git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout master
        git merge upstream/master --no-edit || echo "No changes to merge"
        git push origin master
